/* =========================================================
   Spring Batch Schema for MySQL
   ========================================================= */
DROP TABLE IF EXISTS BATCH_STEP_EXECUTION_CONTEXT;
DROP TABLE IF EXISTS BATCH_STEP_EXECUTION;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_PARAMS;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_CONTEXT;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION;
DROP TABLE IF EXISTS BATCH_JOB_INSTANCE;

DROP TABLE IF EXISTS BATCH_STEP_EXECUTION_SEQ;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_SEQ;
DROP TABLE IF EXISTS BATCH_JOB_SEQ;

-- =========================
-- SEQUENCE TABLES
-- =========================

CREATE TABLE BATCH_JOB_SEQ (
  ID BIGINT NOT NULL,
  UNIQUE_KEY CHAR(1) NOT NULL,
  UNIQUE KEY UNIQUE_KEY_UN (UNIQUE_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE BATCH_JOB_EXECUTION_SEQ (
  ID BIGINT NOT NULL,
  UNIQUE_KEY CHAR(1) NOT NULL,
  UNIQUE KEY UNIQUE_KEY_UN (UNIQUE_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE BATCH_STEP_EXECUTION_SEQ (
  ID BIGINT NOT NULL,
  UNIQUE_KEY CHAR(1) NOT NULL,
  UNIQUE KEY UNIQUE_KEY_UN (UNIQUE_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 초기 시퀀스 값 (필수)
INSERT INTO BATCH_JOB_SEQ (ID, UNIQUE_KEY) VALUES (0, '0');
INSERT INTO BATCH_JOB_EXECUTION_SEQ (ID, UNIQUE_KEY) VALUES (0, '0');
INSERT INTO BATCH_STEP_EXECUTION_SEQ (ID, UNIQUE_KEY) VALUES (0, '0');

-- =========================
-- JOB INSTANCE
-- =========================

CREATE TABLE BATCH_JOB_INSTANCE (
  JOB_INSTANCE_ID BIGINT NOT NULL,
  VERSION BIGINT DEFAULT NULL,
  JOB_NAME VARCHAR(100) NOT NULL,
  JOB_KEY VARCHAR(32) NOT NULL,
  PRIMARY KEY (JOB_INSTANCE_ID),
  UNIQUE KEY JOB_INST_UN (JOB_NAME, JOB_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =========================
-- JOB EXECUTION
-- =========================

CREATE TABLE BATCH_JOB_EXECUTION (
  JOB_EXECUTION_ID BIGINT NOT NULL,
  VERSION BIGINT DEFAULT NULL,
  JOB_INSTANCE_ID BIGINT NOT NULL,
  CREATE_TIME DATETIME(6) NOT NULL,
  START_TIME DATETIME(6) DEFAULT NULL,
  END_TIME DATETIME(6) DEFAULT NULL,
  STATUS VARCHAR(10) DEFAULT NULL,
  EXIT_CODE VARCHAR(2500) DEFAULT NULL,
  EXIT_MESSAGE VARCHAR(2500) DEFAULT NULL,
  LAST_UPDATED DATETIME(6) DEFAULT NULL,
  PRIMARY KEY (JOB_EXECUTION_ID),
  KEY JOB_INST_EXEC_FK (JOB_INSTANCE_ID),
  CONSTRAINT JOB_INST_EXEC_FK
    FOREIGN KEY (JOB_INSTANCE_ID)
    REFERENCES BATCH_JOB_INSTANCE (JOB_INSTANCE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =========================
-- JOB EXECUTION CONTEXT
-- =========================

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT (
  JOB_EXECUTION_ID BIGINT NOT NULL,
  SHORT_CONTEXT VARCHAR(2500) NOT NULL,
  SERIALIZED_CONTEXT TEXT,
  PRIMARY KEY (JOB_EXECUTION_ID),
  CONSTRAINT JOB_EXEC_CTX_FK
    FOREIGN KEY (JOB_EXECUTION_ID)
    REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =========================
-- JOB EXECUTION PARAMS
-- =========================

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS (
  JOB_EXECUTION_ID BIGINT NOT NULL,
  PARAMETER_NAME VARCHAR(100) NOT NULL,
  PARAMETER_TYPE VARCHAR(100) NOT NULL,
  PARAMETER_VALUE VARCHAR(2500),
  IDENTIFYING CHAR(1) NOT NULL,
  KEY JOB_EXEC_PARAMS_FK (JOB_EXECUTION_ID),
  CONSTRAINT JOB_EXEC_PARAMS_FK
    FOREIGN KEY (JOB_EXECUTION_ID)
    REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =========================
-- STEP EXECUTION
-- =========================

CREATE TABLE BATCH_STEP_EXECUTION (
  STEP_EXECUTION_ID BIGINT NOT NULL,
  VERSION BIGINT NOT NULL,
  STEP_NAME VARCHAR(100) NOT NULL,
  JOB_EXECUTION_ID BIGINT NOT NULL,
  CREATE_TIME DATETIME(6) NOT NULL,
  START_TIME DATETIME(6) DEFAULT NULL,
  END_TIME DATETIME(6) DEFAULT NULL,
  STATUS VARCHAR(10) DEFAULT NULL,
  COMMIT_COUNT BIGINT DEFAULT NULL,
  READ_COUNT BIGINT DEFAULT NULL,
  FILTER_COUNT BIGINT DEFAULT NULL,
  WRITE_COUNT BIGINT DEFAULT NULL,
  READ_SKIP_COUNT BIGINT DEFAULT NULL,
  WRITE_SKIP_COUNT BIGINT DEFAULT NULL,
  PROCESS_SKIP_COUNT BIGINT DEFAULT NULL,
  ROLLBACK_COUNT BIGINT DEFAULT NULL,
  EXIT_CODE VARCHAR(2500) DEFAULT NULL,
  EXIT_MESSAGE VARCHAR(2500) DEFAULT NULL,
  LAST_UPDATED DATETIME(6) DEFAULT NULL,
  PRIMARY KEY (STEP_EXECUTION_ID),
  KEY JOB_EXEC_STEP_FK (JOB_EXECUTION_ID),
  CONSTRAINT JOB_EXEC_STEP_FK
    FOREIGN KEY (JOB_EXECUTION_ID)
    REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =========================
-- STEP EXECUTION CONTEXT
-- =========================

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT (
  STEP_EXECUTION_ID BIGINT NOT NULL,
  SHORT_CONTEXT VARCHAR(2500) NOT NULL,
  SERIALIZED_CONTEXT TEXT,
  PRIMARY KEY (STEP_EXECUTION_ID),
  CONSTRAINT STEP_EXEC_CTX_FK
    FOREIGN KEY (STEP_EXECUTION_ID)
    REFERENCES BATCH_STEP_EXECUTION (STEP_EXECUTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
